// Generated by gencpp from file point_msgs/Point.msg
// DO NOT EDIT!


#ifndef POINT_MSGS_MESSAGE_POINT_H
#define POINT_MSGS_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace point_msgs
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : data()
    , vel(0.0)  {
    }
  Point_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , vel(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;

   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::point_msgs::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_msgs::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::point_msgs::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::point_msgs::Point > PointPtr;
typedef boost::shared_ptr< ::point_msgs::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_msgs::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_msgs::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace point_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'point_msgs': ['/home/mason/catkin_ws/src/point_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::point_msgs::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_msgs::Point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_msgs::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_msgs::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_msgs::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_msgs::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6f9f9c6cebad27e7295a45a8afd08e6";
  }

  static const char* value(const ::point_msgs::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6f9f9c6cebad27eULL;
  static const uint64_t static_value2 = 0x7295a45a8afd08e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_msgs/Point";
  }

  static const char* value(const ::point_msgs::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n\
float32 vel\n\
# geometry_msgs/Pose pose\n\
# string name\n\
";
  }

  static const char* value(const ::point_msgs::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_msgs::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_msgs::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_msgs::Point_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_MSGS_MESSAGE_POINT_H
